apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  # PV name
  volumeName: "efs-static"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-static-pod
  labels:
    purpose: "efs-static-demo"
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persisten-storage
      path: /usr/share/nginx/html
  volumes:
  - name: persisten-storage
    PersistentVolumeClaim:
     claimName: efs-static