apiVersion: v1
kind: Pod
metadata:
  name: env-variables
spec:
  containers:
  - name: env
    image: nginx
    env:
    - name: project
      value: expense
    - name: evironment
      value: "prod environtment"
    - name: Name
      value: "Naveen Rajoli"
