apiVersion: v1
kind: Pod
metadata:
  name: cpu-mem
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
    # soft limit
      requestes:
        memory: "64mi"
        cpu: "100m"
    # hard limit
      limits:
        memory: "128mi"
        cpu: "150m" 