apiVersion: v1
kind: Pod
metadata:
  name: cpu-mem
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
    # soft limit
      requests:
        memory: "60mi"
        cpu: "100m"
    # hard limit
      limits:
        memory: "120mi"
        cpu: "150m" 