apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
spec:
  type: NodePort
  selector:
    name: naveenrajoli
    environment: prod
    project: expense
    component: nodeport-svc-web
    version: "1.0.0"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
---

apiVersion: v1
kind: Pod
metadata:
  name: nginxnode
  labels:
    name: naveenrajoli
    environment: prod
    project: expense
    component: nodeport-svc-web
    version: "1.0.0"
spec:
  containers:
  - name: nginx
    image: nginx