apiVersion: v1
kind: Service
metadata:
  name: nodeport-svac
spec:
  type: NodePort
  selector:
    name: naveenrajoli
    environment: prod
    project: expense
    component: nodeport-svc-web
    version: "1.0.1"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30008
---

apiVersion: v1
kind: Pod
metadata:
  name: nginxnodeqqq
  labels:
    name: naveenrajoli
    environment: prod
    project: expense
    component: nodeport-svc-web
    version: "1.0.1"
spec:
  containers:
  - name: nginx
    image: nginx