apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    name: naveenrajoli
    environment: prod
    project: expense
    component: LoadBalancer-svc-web
    version: "1.0.0"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30009
---

apiVersion: v1
kind: Pod
metadata:
  name: nginxlb
  labels:
    name: naveenrajoli
    environment: prod
    project: expense
    component: LoadBalancer-svc-web
    version: "1.0.0"
spec:
  containers:
  - name: nginx
    image: nginx