apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-dep
    # labels of deployment resource
  labels:
    app: frontend-dep
    tier: web-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-dep
      tier: web-dep
  template:
    metadata:
      labels:
        app: frontend-dep
        tier: web-dep
    spec:
      containers:
      - name: nginx
        image: naveenrajoli/nginxdeploy:1.1
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: deployment-svc
spec:
  type: LoadBalancer
  selector:
    app: frontend-dep
    tier: web-dep
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
